- id: 0
- id: 1
  name: Audeze LCD-3 Over Ear Headphones Fazor Elements
  short-name: Audeze LCD-3
  imgs: [ "udeze-lcd-3-over.jpg" ]
  asin: B00O12MH1S
- id: 2
  name: Yamaha P45 - Digital Piano
  short-name: Yamaha P-45B
  imgs: [ "yamaha-p45-88-key.jpg" ]
  asin: B00UJ9LNDK
- id: 3
  name: Audeze Mobius Premium 3D Gaming Headset with Surround Sound
  short-name: Audeze Mobius headset
  imgs: [ "audeze-mobius-premium-3d.jpg" ]
  asin: B07BDQZ52Z
- id: 3.1
  name: Nuraphone - Wireless Bluetooth Over Ear Headphones With Earbuds
  short-name: Nuraphone Wireless Headphones
  imgs: [ "nuraphone-wireless-over-the.jpg" ]
  asin: B076X4KH11
- id: 4
  name: Ruputas Wowstick 1F+ Electric Screwdriver and Repair Kit
  short-name: Ruputas Wowstick 1F+
  imgs: [ "ruputas-wowstick-1f-electric.jpg" ]
  asin: B076X4KH11
- id: 5
  name: iFixit Pro Tech Toolkit - Electronics, Smartphone, Computer & Tablet Repair Kit
  short-name: iFixit Pro Tech Toolkit
  imgs: [ ]
  asin: B01GF0KV6G
- id: 6
  name: Bang & Olufsen B&O Play H8i
  short-name: B&O Beoplay H8i
  imgs: [ "bang-and-olufsen-play.jpg" ]
  asin: B078HPHLPR
- id: 7
  name: Neato Robotics D7 Connected Laser Guided Smart Robot Vacuum
  short-name: Neato Robotics D7
  imgs: [ "neato-robotics-d7-robot.jpg" ]
  asin: B078MPFN55
- id: 8
  name: Apple iMac 27-inch Retina 5K
  short-name: iMac Retina 5K
  imgs: [ "apple-imac-27-inch.jpg" ]
  asin: B07Q1NBCVB
- id: 9
  name: Audeze LCD-4 Over Ear Headphones
  short-name: Audeze LCD-4
  imgs: [ "audeze-lcd-4-over.jpg" ]
  asin: B01DTQ6AMS
- id: 10
  name: Audeze LCD-3 Over Ear Headphones Fazor Elements MAPLE WOOD VERSION
  short-name: Audeze LCD-3
  imgs: [ "audeze-lcd-3-wood.jpg" ]
  asin: B07D9WWKTS
- id: 11
  name: HIFIMAN HE1000 V2 Over Ear Headphones
  short-name: HIFIMAN HE1000 V2
  imgs: [ "hifiman-he1000-v2-over.jpg" ]
  asin: B01I50644C
- id: 12
  name: iRobot Roomba 980 Robot Vacuum
  short-name: iRobot Roomba 980
  imgs: [ "irobot-roomba-980-robot.jpg" ]
  asin: B013E9L4ZS
- id: 13
  name: Acer Predator Helios 300 Gaming Laptop
  short-name: Acer Preditor helios 300
  imgs: [ "acer-predator-helios-300.jpg" ]
  asin: B07CTHLX8C
- id: 14
  name: 2019 HP Premium HD Laptop
  short-name: 2019 HP Premium HD Laptop
  imgs: [ "hp-premium-hd-laptop.jpg" ]
  asin: B07QKWTZ4B
- id: 15
  name: Canon EOS Rebel T6 Digital SLR Camera Kit with EF-S 18-55mm f/3.5-5.6 IS II Lens (Black)
  short-name: Canon EOS Rebel T6
  imgs: [ "canon-eos-rebel-t6.jpg" ]
  asin: B01CO2JPYS
- id: 16
  name: Arsvita Car Audio Bluetooth Cassette Receiver
  short-name: Arsvita Car Audio Bluetooth Cassette Receiver
  imgs: [ "arsvita-car-audio-bluetooth.jpg" ]
  asin: B07QSW6KNY
- id: 17
  name: MSI GeForce GTX 1080
  short-name: MSI Geforce GTX 1080
  imgs: [ "msi-geforce-gtx-1080.jpg" ]
  asin: B01HHBQBLG
- id: 18
  name: Concept2 Model D Indoor Rowing Machine
  short-name: Concept2 Rowing Machine
  imgs: [ "concept2-model-d-indoor.jpg" ]
  asin: B00NH9WEUA
- id: 19
  name: CyberpowerPC Gamer Xtreme VR Gaming PC
  short-name: CyberpowerPC Gamer Xtreme VR Gaming PC
  imgs: [ "cyberpowerpc-gamer-xtreme-vr.jpg" ]
  asin: B07PKXQBHN
- id: 20
  name: Doona Infant Car Seat & Latch Base
  short-name: Doona Infant car seat
  imgs: [ "doona-infant-car-seat.jpg" ]
  asin: B07HML1BT5
- id: 21
  name: NETGEAR Nighthawk Smart WIFI Router
  short-name: NETGEAR Nighthawk WIFI Router
  imgs: [ "netgear-nighthawk-smart-wifi.jpg" ]
  asin: B07C65K9H9
- id: 22
  name: NordicTrack T Series 6.5S and 6.5Si Treadmill
  short-name: NordicTrack T Series
  imgs: [ "nordictrack-tseries-65s-65si.jpg" ]
  asin: B0193V3DJ6
- id: 23
  name: Oculus Rift S PC-Powered VR Gaming Headset
  short-name: Oculus Rift S
  imgs: [ "oculus-rift-s-pc.jpg" ]
  asin: B07PTMKYS7
- id: 24
  name: SimpliSafe 12- Piece Home Security System with HD Camera and Smoke Detector
  short-name: SimpliSafe Home Security System
  imgs: [ "simplisafe-12-piece-home.jpg" ]
  asin: B07C4WT5LQ
- id: 25
  name: MDMA Therapy Home Kit For Cat Depression
  short-name: ""
  imgs: [ "mdma-cat-depression-therapy.jpg" ]
- id: 26
  name: Destroy the Amazon rainforest for charity with Amazonian wood clothing
  short-name: ""
  url: ""
  imgs: [ "amazon-wood-clothing-review.jpg" ]
- id: 27
  name: Audeze LCD-X Over Ear Open Back Headphone with New Suspension Headband Creator Package – no Travel case
  short-name: Audeze LCD-X
  url: ""
  imgs: [ "audeze-lcd-x-over.jpg" ]
  asin: B0765KJ5CB
- id: 28
  name: DELONGHI ESAM3300 Super Automatic Espresso/Coffee Machine
  short-name: DELONGHI ESAM3300
  url: ""
  imgs: [ "delonghi-3300.jpg" ]
  asin: B000N2YKQ0
